### PR TITLE
keyring 23.0.1

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Updated meta.yaml to 23.0.1.

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
```
v23.0.1
#504: Better error with invalid parameter to init_keyring.
#505: Nicer documentation for headless Docker.
v23.0.0
Backends now all invoke set_properties_from_env on self in the initializer. Derived backends should be sure to invoke super().__init__().
v22.4.0
Use new entry points API from importlib_metadata 3.6.
```

**Review by varlackc — APPROVED** [review]
The package is coming from the right place
The package is relatively popular with 963,118 downloads at the time of the review
The change is a Mayor version change from 22.3.0 to 23.0.1
There were no breaking changes mentioned in the changelog, however there were some changes on the way that the API from importlib_metadata 3.6 is called internally
https://github.com/jaraco/keyring/blob/main/CHANGES.rst
Records indicate that the package was released in March 25 2021
There were no significant open issues in the upstream
The License in the recipe is correct
The package builds correctly on concourse

**Comment by ansthomas** [comment]
1. It would be good , if you remove the commented out part below part (It was not there in our recipe)
    # - cross-python_{{ target_platform }}     # [build_platform != target_platform]

2. It would be good if you add back the descriptions and urls as below. It helps for basic understanding of the package. (I see the url has changed and I copied the correct one below):
- description: |
    the python keyring lib provides a easy way to access the system keyring
    service from python.  it can be used in any application that needs safe
    password storage.
  doc_url: https://pypi.org/project/keyring/
  doc_source_url: https://github.com/jaraco/keyring/blob/main/README.rst

**Review by ansthomas — APPROVED** [review]

**Comment by skupr-anaconda** [comment]
It should be merged after Anaconda Release 2021.04

**Pull request closed without merging**
